export { createTestEnemy } from './test-enemy.factory';
export { createTestBoard } from './test-board.factory';
export {
  createGameBoardServiceSpy,
  createEnemyServiceSpy,
  createGameStatsServiceSpy,
  createTutorialServiceSpy,
  createCombatLoopServiceSpy,
  createMinimapServiceSpy,
  createSettingsServiceSpy,
  createAudioServiceSpy,
  createSceneServiceSpy,
  createGameNotificationServiceSpy,
  createTowerAnimationServiceSpy,
  createMapBridgeServiceSpy,
  createMapStorageServiceSpy,
  createPlayerProfileServiceSpy,
  createGameStateServiceSpy,
  createGameEndServiceSpy,
  createWaveServiceSpy,
  createTowerCombatServiceSpy,
  createStatusEffectServiceSpy,
  createChallengeTrackingServiceSpy,
  createGamePauseServiceSpy,
  createChallengeDisplayServiceSpy,
  createTowerPlacementServiceSpy,
  createTowerSelectionServiceSpy,
  // createProjectileServiceSpy removed (M2 S5 — projectile.service.ts deleted)
  createTowerUpgradeVisualServiceSpy,
  createGameSessionServiceSpy,
  createRelicServiceSpy,
  createRunServiceSpy,
  createDeckServiceSpy,
  createCardEffectServiceSpy,
  createScreenShakeServiceSpy,
} from './test-spies.factory';
